#!/bin/bash
# Backup important files across the network.
echo Backing up work files...
rsync -av --no-g --no-t --delete --progress /home/blacklaw/Dropbox/ blacklaw.homedns.org:/media/Seagate320/Dropbox/
echo Backing up music...
rsync -av --no-g --no-t --delete --progress /media/Data/My\ Music/ blacklaw.homedns.org:/media/Seagate320/Music/
echo Backing up photographs...
rsync -av --no-g --delete --progress /media/Data/Photos/ blacklaw.homedns.org:/media/Seagate320/Photos/
